/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_victorcruz;

import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor Jafet Cruz
 */
public class Lab8P2_VictorCruz extends javax.swing.JFrame {

    /**
     * Creates new form Lab8P2_VictorCruz
     */
    public Lab8P2_VictorCruz() {
        initComponents();
        DefaultComboBoxModel m1= (DefaultComboBoxModel) CB_CategoriaCarro.getModel();
        m1.addElement("N/A");
        m1.addElement("Generalista");
        m1.addElement("Prenium");
        m1.addElement("Deportivo");
        CB_CategoriaCarro.setModel(m1);
        DefaultComboBoxModel m2= (DefaultComboBoxModel) CB_TipoCarro.getModel();
        m2.addElement("N/A");
        m2.addElement("Sedan");
        m2.addElement("Familiar");
        m2.addElement("HatchBack");
        m2.addElement("FastBack");
        m2.addElement("SUV");
        CB_TipoCarro.setModel(m2);
        DefaultComboBoxModel m3= (DefaultComboBoxModel) CB_TipoMotorCarro.getModel();
        m3.addElement("N/A");
        m3.addElement("Combustion");
        m3.addElement("Electrico");
        CB_TipoMotorCarro.setModel(m3);
        DefaultComboBoxModel m4= (DefaultComboBoxModel) CB_TipoHibrido.getModel();
        m4.addElement("N/A");
        m4.addElement("MicroHibrido");
        m4.addElement("Hibrido Convencional");
        m4.addElement("Hibrido Enchufable");
        m4.addElement("Hibrido Electrico");
        CB_TipoHibrido.setModel(m4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_AdminCarro = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        JB_AgregarCarro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JB_ModificarCarro = new javax.swing.JButton();
        JB_EliminarCarro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_ListarCarros = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        CB_CategoriaCarro = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        TF_VIN = new javax.swing.JTextField();
        CB_MarcaCarro = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CB_TipoCarro = new javax.swing.JComboBox<>();
        JS_NumeroPuertas = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        TF_ColorCarro = new javax.swing.JTextField();
        CB_TipoMotorCarro = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TF_PrecioCarro = new javax.swing.JTextField();
        CB_TipoHibrido = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        JS_CantPasajeros = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        JS_TiempoEnsamblaje = new javax.swing.JSpinner();
        JB_Prepar_Marca = new javax.swing.JButton();
        JD_BuscarVIN = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TF_BuscarVIN = new javax.swing.JTextField();
        JB_BuscarVIN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JT_BusquedaVIN = new javax.swing.JTable();
        JD_BuscarAtributoLibre = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        JT_BusquedaAtributo = new javax.swing.JTable();
        TF_BuscarAtriburoLibre = new javax.swing.JTextField();
        JB_BuscarAtributoLibre = new javax.swing.JButton();
        JD_BuscarCategoria = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        JT_BusquedaCategoria = new javax.swing.JTable();
        TF_BuscarCategoria = new javax.swing.JTextField();
        JB_BuscarCategoria = new javax.swing.JButton();
        JD_BuscarMarcas = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        JT_BusquedaMarcas = new javax.swing.JTable();
        TF_BuscarMarcas = new javax.swing.JTextField();
        JB_BuscarMarcas = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        JB_SalirSistema = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTA_InfoCarros = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_AdminCarros = new javax.swing.JMenu();
        JMI_CRUDCarros = new javax.swing.JMenuItem();
        JM_Busqueda = new javax.swing.JMenu();
        JMI_BusquedaVIN = new javax.swing.JMenuItem();
        JMI_BusquedaCategoria = new javax.swing.JMenuItem();
        JMI_BusquedaAtributoLibre = new javax.swing.JMenuItem();
        JMI_BusquedaMarcas = new javax.swing.JMenuItem();

        JD_AdminCarro.setTitle("Administracion Carros");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel12.setText("Carros");

        JB_AgregarCarro.setText("Agregar");
        JB_AgregarCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarCarroMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Listar Carros");

        JB_ModificarCarro.setText("Modificar");
        JB_ModificarCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_ModificarCarroMouseClicked(evt);
            }
        });

        JB_EliminarCarro.setText("Eliminar");
        JB_EliminarCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EliminarCarroMouseClicked(evt);
            }
        });

        JT_ListarCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Color", "Marca", "VIN", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JT_ListarCarros);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel18.setText("Categoria: ");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel19.setText("VIN:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel20.setText("Marca: ");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel21.setText("Tipo de Auto: ");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel22.setText("Numero de puertas: ");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel23.setText("Color: ");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel24.setText("Tipo de motor: ");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel27.setText("Precio: ");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel26.setText("Tipo de Hibrido: ");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel25.setText("Cantidad Maxima de Pasajeros: ");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel28.setText("Ensamblaje(en segundos): ");

        JB_Prepar_Marca.setText(" Marcas");
        JB_Prepar_Marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_Prepar_MarcaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_AdminCarroLayout = new javax.swing.GroupLayout(JD_AdminCarro.getContentPane());
        JD_AdminCarro.getContentPane().setLayout(JD_AdminCarroLayout);
        JD_AdminCarroLayout.setHorizontalGroup(
            JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdminCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_AdminCarroLayout.createSequentialGroup()
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_ColorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_VIN, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JS_NumeroPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JD_AdminCarroLayout.createSequentialGroup()
                                .addComponent(CB_CategoriaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JB_Prepar_Marca))
                            .addComponent(CB_MarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_TipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TF_PrecioCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(JD_AdminCarroLayout.createSequentialGroup()
                            .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24)
                                .addComponent(jLabel27)
                                .addComponent(jLabel26))
                            .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(JD_AdminCarroLayout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(CB_TipoMotorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_AdminCarroLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CB_TipoHibrido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JB_AgregarCarro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JD_AdminCarroLayout.createSequentialGroup()
                            .addComponent(jLabel28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JS_TiempoEnsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JD_AdminCarroLayout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JS_CantPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JD_AdminCarroLayout.createSequentialGroup()
                        .addComponent(JB_ModificarCarro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_EliminarCarro)))
                .addGap(66, 66, 66))
            .addGroup(JD_AdminCarroLayout.createSequentialGroup()
                .addGap(543, 543, 543)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_AdminCarroLayout.setVerticalGroup(
            JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_AdminCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(46, 46, 46)
                .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_AdminCarroLayout.createSequentialGroup()
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CB_CategoriaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JB_Prepar_Marca)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(TF_VIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(CB_MarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(CB_TipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(JS_NumeroPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(TF_ColorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(CB_TipoMotorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(TF_PrecioCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(CB_TipoHibrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(JS_CantPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_AdminCarroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JB_ModificarCarro)
                            .addComponent(JB_EliminarCarro))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_AdminCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(JS_TiempoEnsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JB_AgregarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        JD_BuscarVIN.setTitle("Busqueda VIN");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setText("Busqueda por VIN");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Buscar:");

        JB_BuscarVIN.setText("Resultados");
        JB_BuscarVIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_BuscarVINMouseClicked(evt);
            }
        });

        JT_BusquedaVIN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Color", "Marca", "VIN", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(JT_BusquedaVIN);

        javax.swing.GroupLayout JD_BuscarVINLayout = new javax.swing.GroupLayout(JD_BuscarVIN.getContentPane());
        JD_BuscarVIN.getContentPane().setLayout(JD_BuscarVINLayout);
        JD_BuscarVINLayout.setHorizontalGroup(
            JD_BuscarVINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_BuscarVINLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(JD_BuscarVINLayout.createSequentialGroup()
                .addGroup(JD_BuscarVINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_BuscarVINLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(TF_BuscarVIN, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_BuscarVIN))
                    .addGroup(JD_BuscarVINLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_BuscarVINLayout.setVerticalGroup(
            JD_BuscarVINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_BuscarVINLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(116, 116, 116)
                .addGroup(JD_BuscarVINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JB_BuscarVIN)
                    .addComponent(TF_BuscarVIN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        JD_BuscarAtributoLibre.setTitle("Busqueda Atributo");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel11.setText("Busqueda por Atributo");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Buscar(Menos VIN,Categoria y Marcas):");

        JT_BusquedaAtributo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Color", "Tipo", "Motor", "Tipo Hibrido", "Numero de Puertas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(JT_BusquedaAtributo);

        JB_BuscarAtributoLibre.setText("Resultados");
        JB_BuscarAtributoLibre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_BuscarAtributoLibreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_BuscarAtributoLibreLayout = new javax.swing.GroupLayout(JD_BuscarAtributoLibre.getContentPane());
        JD_BuscarAtributoLibre.getContentPane().setLayout(JD_BuscarAtributoLibreLayout);
        JD_BuscarAtributoLibreLayout.setHorizontalGroup(
            JD_BuscarAtributoLibreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_BuscarAtributoLibreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_BuscarAtriburoLibre, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(JB_BuscarAtributoLibre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_BuscarAtributoLibreLayout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(JD_BuscarAtributoLibreLayout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_BuscarAtributoLibreLayout.setVerticalGroup(
            JD_BuscarAtributoLibreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_BuscarAtributoLibreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(116, 116, 116)
                .addGroup(JD_BuscarAtributoLibreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(JB_BuscarAtributoLibre)
                    .addComponent(TF_BuscarAtriburoLibre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        JD_BuscarCategoria.setTitle("Busqueda Categoria");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel14.setText("Busqueda por Categoria");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Buscar:");

        JT_BusquedaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Color", "Marca", "VIN", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(JT_BusquedaCategoria);

        JB_BuscarCategoria.setText("Resultados");
        JB_BuscarCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_BuscarCategoriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_BuscarCategoriaLayout = new javax.swing.GroupLayout(JD_BuscarCategoria.getContentPane());
        JD_BuscarCategoria.getContentPane().setLayout(JD_BuscarCategoriaLayout);
        JD_BuscarCategoriaLayout.setHorizontalGroup(
            JD_BuscarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_BuscarCategoriaLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(JD_BuscarCategoriaLayout.createSequentialGroup()
                .addGroup(JD_BuscarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_BuscarCategoriaLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(TF_BuscarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_BuscarCategoria))
                    .addGroup(JD_BuscarCategoriaLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_BuscarCategoriaLayout.setVerticalGroup(
            JD_BuscarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_BuscarCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(116, 116, 116)
                .addGroup(JD_BuscarCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(JB_BuscarCategoria)
                    .addComponent(TF_BuscarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        JD_BuscarMarcas.setTitle("Busqueda Marcas");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel16.setText("Busqueda por Marcas");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Buscar:");

        JT_BusquedaMarcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoria", "Color", "Marca", "VIN", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(JT_BusquedaMarcas);

        JB_BuscarMarcas.setText("Resultados");
        JB_BuscarMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_BuscarMarcasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_BuscarMarcasLayout = new javax.swing.GroupLayout(JD_BuscarMarcas.getContentPane());
        JD_BuscarMarcas.getContentPane().setLayout(JD_BuscarMarcasLayout);
        JD_BuscarMarcasLayout.setHorizontalGroup(
            JD_BuscarMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_BuscarMarcasLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(JD_BuscarMarcasLayout.createSequentialGroup()
                .addGroup(JD_BuscarMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_BuscarMarcasLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(TF_BuscarMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_BuscarMarcas))
                    .addGroup(JD_BuscarMarcasLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_BuscarMarcasLayout.setVerticalGroup(
            JD_BuscarMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_BuscarMarcasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(116, 116, 116)
                .addGroup(JD_BuscarMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(JB_BuscarMarcas)
                    .addComponent(TF_BuscarMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU ADMINISTRADOR");

        jToolBar1.setRollover(true);

        JB_SalirSistema.setText("Salir del Sistema");
        JB_SalirSistema.setFocusable(false);
        JB_SalirSistema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_SalirSistema.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JB_SalirSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_SalirSistemaMouseClicked(evt);
            }
        });
        jToolBar1.add(JB_SalirSistema);

        JTA_InfoCarros.setColumns(20);
        JTA_InfoCarros.setRows(5);
        jScrollPane2.setViewportView(JTA_InfoCarros);

        JM_AdminCarros.setText("Admin Carros");

        JMI_CRUDCarros.setText("CRUD CARROS");
        JMI_CRUDCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CRUDCarrosActionPerformed(evt);
            }
        });
        JM_AdminCarros.add(JMI_CRUDCarros);

        jMenuBar1.add(JM_AdminCarros);

        JM_Busqueda.setText("Busqueda");

        JMI_BusquedaVIN.setText("Busqueda por VIN");
        JMI_BusquedaVIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_BusquedaVINActionPerformed(evt);
            }
        });
        JM_Busqueda.add(JMI_BusquedaVIN);

        JMI_BusquedaCategoria.setText("Budqueda por Categoria");
        JMI_BusquedaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_BusquedaCategoriaActionPerformed(evt);
            }
        });
        JM_Busqueda.add(JMI_BusquedaCategoria);

        JMI_BusquedaAtributoLibre.setText("Busqueda Atributo Libre");
        JMI_BusquedaAtributoLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_BusquedaAtributoLibreActionPerformed(evt);
            }
        });
        JM_Busqueda.add(JMI_BusquedaAtributoLibre);

        JMI_BusquedaMarcas.setText("Busqueda por Marcas");
        JMI_BusquedaMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_BusquedaMarcasActionPerformed(evt);
            }
        });
        JM_Busqueda.add(JMI_BusquedaMarcas);

        jMenuBar1.add(JM_Busqueda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_CRUDCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CRUDCarrosActionPerformed
        AdminCarro();
    }//GEN-LAST:event_JMI_CRUDCarrosActionPerformed

    private void JMI_BusquedaVINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_BusquedaVINActionPerformed
        // TODO add your handling code here:
        BusquedaVIN();
    }//GEN-LAST:event_JMI_BusquedaVINActionPerformed

    private void JMI_BusquedaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_BusquedaCategoriaActionPerformed
        // TODO add your handling code here:
        BusquedaCategoria();
    }//GEN-LAST:event_JMI_BusquedaCategoriaActionPerformed

    private void JMI_BusquedaAtributoLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_BusquedaAtributoLibreActionPerformed
        // TODO add your handling code here:
        BusquedaAtributo();
    }//GEN-LAST:event_JMI_BusquedaAtributoLibreActionPerformed

    private void JB_BuscarVINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_BuscarVINMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_JB_BuscarVINMouseClicked

    private void JB_SalirSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_SalirSistemaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_JB_SalirSistemaMouseClicked

    private void JB_EliminarCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EliminarCarroMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_JB_EliminarCarroMouseClicked

    private void JB_ModificarCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ModificarCarroMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_JB_ModificarCarroMouseClicked

    private void JB_AgregarCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarCarroMouseClicked
        String t_carro=  "";
        String t_motor= "";
        String  hybrid= "";
        String  categoria= "";
        String  marca= "";
        Object cat_carro = CB_CategoriaCarro.getSelectedItem();
        Object mar_carro = CB_MarcaCarro.getSelectedItem();
        Object tipo_carro = CB_TipoCarro.getSelectedItem();
        Object motor_carro = CB_TipoMotorCarro.getSelectedItem();
        Object t_hibrido = CB_TipoHibrido.getSelectedItem();
        categoria+=cat_carro;
        marca+=mar_carro;
        t_carro+=tipo_carro;
        t_motor+=motor_carro;
        hybrid+=t_hibrido;
        
        
        
        Dba db = new Dba("Carros.mdb");
        db.conectar();
        try {
            db.query.execute("INSERT INTO carros"
                    + " (categoria,VIN,marca,tipo,puertas,color,motor,precio,hibrido,"
                    + "pasajeros,tiempo)"
                    + " VALUES ('" + categoria
                    + "', '" + TF_VIN.getText()
                    + "', '" + marca
                    + "', '" + t_carro
                    + "', '" + JS_NumeroPuertas.getValue()
                    + "', '" + TF_ColorCarro.getText()
                    + "', '" + t_motor
                    + "', '" + Integer.parseInt(TF_PrecioCarro.getText())
                    + "', '" + hybrid
                    + "', "
                    + "'" + JS_CantPasajeros.getValue()
                    + "', '" + JS_TiempoEnsamblaje.getValue() + "')");
            db.commit();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        db.desconectar();

    }//GEN-LAST:event_JB_AgregarCarroMouseClicked

    private void JB_BuscarAtributoLibreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_BuscarAtributoLibreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_BuscarAtributoLibreMouseClicked

    private void JB_BuscarCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_BuscarCategoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_BuscarCategoriaMouseClicked

    private void JB_BuscarMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_BuscarMarcasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_BuscarMarcasMouseClicked

    private void JMI_BusquedaMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_BusquedaMarcasActionPerformed
        BusquedaMarcas();
    }//GEN-LAST:event_JMI_BusquedaMarcasActionPerformed

    private void JB_Prepar_MarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_Prepar_MarcaMouseClicked
        // TODO add your handling code here:
        int check=CB_CategoriaCarro.getSelectedIndex();
        DefaultComboBoxModel modelo= (DefaultComboBoxModel) CB_MarcaCarro.getModel();
        modelo.removeAllElements();
        CB_MarcaCarro.setModel(modelo);
        if(check==1){
             DefaultComboBoxModel modelo1= (DefaultComboBoxModel) CB_MarcaCarro.getModel();
             modelo1.addElement("Seat");
             modelo1.addElement("SKoda");
             CB_MarcaCarro.setModel(modelo1);
        }else if(check==2){
             DefaultComboBoxModel modelo1= (DefaultComboBoxModel) CB_MarcaCarro.getModel();
             modelo1.addElement("Audi");
             modelo1.addElement("Volkswagen");
             modelo1.addElement("Bently");
             CB_MarcaCarro.setModel(modelo1);
        }else if(check==3){
             DefaultComboBoxModel modelo1= (DefaultComboBoxModel) CB_MarcaCarro.getModel();
             modelo1.addElement("Porsche");
             modelo1.addElement("Lamborghini");
             modelo1.addElement("Bugatti");
             CB_MarcaCarro.setModel(modelo1);
        }else{
            JOptionPane.showMessageDialog(JD_AdminCarro, "Por favor selecione un opcion que no sea N/A ");
        }
        
    }//GEN-LAST:event_JB_Prepar_MarcaMouseClicked

    public void AdminCarro() {
        JD_AdminCarro.pack();
        JD_AdminCarro.setModal(true);
        JD_AdminCarro.setLocationRelativeTo(this);
        JD_AdminCarro.setVisible(true);
    }

    public void BusquedaMarcas() {
        JD_BuscarMarcas.pack();
        JD_BuscarMarcas.setModal(true);
        JD_BuscarMarcas.setLocationRelativeTo(this);
        JD_BuscarMarcas.setVisible(true);
    }

    public void BusquedaAtributo() {
        JD_BuscarAtributoLibre.pack();
        JD_BuscarAtributoLibre.setModal(true);
        JD_BuscarAtributoLibre.setLocationRelativeTo(this);
        JD_BuscarAtributoLibre.setVisible(true);
    }

    public void BusquedaVIN() {
        JD_BuscarVIN.pack();
        JD_BuscarVIN.setModal(true);
        JD_BuscarVIN.setLocationRelativeTo(this);
        JD_BuscarVIN.setVisible(true);
    }

    public void BusquedaCategoria() {
        JD_BuscarCategoria.pack();
        JD_BuscarCategoria.setModal(true);
        JD_BuscarCategoria.setLocationRelativeTo(this);
        JD_BuscarCategoria.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab8P2_VictorCruz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_CategoriaCarro;
    private javax.swing.JComboBox<String> CB_MarcaCarro;
    private javax.swing.JComboBox<String> CB_TipoCarro;
    private javax.swing.JComboBox<String> CB_TipoHibrido;
    private javax.swing.JComboBox<String> CB_TipoMotorCarro;
    private javax.swing.JButton JB_AgregarCarro;
    private javax.swing.JButton JB_BuscarAtributoLibre;
    private javax.swing.JButton JB_BuscarCategoria;
    private javax.swing.JButton JB_BuscarMarcas;
    private javax.swing.JButton JB_BuscarVIN;
    private javax.swing.JButton JB_EliminarCarro;
    private javax.swing.JButton JB_ModificarCarro;
    private javax.swing.JButton JB_Prepar_Marca;
    private javax.swing.JButton JB_SalirSistema;
    private javax.swing.JDialog JD_AdminCarro;
    private javax.swing.JDialog JD_BuscarAtributoLibre;
    private javax.swing.JDialog JD_BuscarCategoria;
    private javax.swing.JDialog JD_BuscarMarcas;
    private javax.swing.JDialog JD_BuscarVIN;
    private javax.swing.JMenuItem JMI_BusquedaAtributoLibre;
    private javax.swing.JMenuItem JMI_BusquedaCategoria;
    private javax.swing.JMenuItem JMI_BusquedaMarcas;
    private javax.swing.JMenuItem JMI_BusquedaVIN;
    private javax.swing.JMenuItem JMI_CRUDCarros;
    private javax.swing.JMenu JM_AdminCarros;
    private javax.swing.JMenu JM_Busqueda;
    private javax.swing.JSpinner JS_CantPasajeros;
    private javax.swing.JSpinner JS_NumeroPuertas;
    private javax.swing.JSpinner JS_TiempoEnsamblaje;
    private javax.swing.JTextArea JTA_InfoCarros;
    private javax.swing.JTable JT_BusquedaAtributo;
    private javax.swing.JTable JT_BusquedaCategoria;
    private javax.swing.JTable JT_BusquedaMarcas;
    private javax.swing.JTable JT_BusquedaVIN;
    private javax.swing.JTable JT_ListarCarros;
    private javax.swing.JTextField TF_BuscarAtriburoLibre;
    private javax.swing.JTextField TF_BuscarCategoria;
    private javax.swing.JTextField TF_BuscarMarcas;
    private javax.swing.JTextField TF_BuscarVIN;
    private javax.swing.JTextField TF_ColorCarro;
    private javax.swing.JTextField TF_PrecioCarro;
    private javax.swing.JTextField TF_VIN;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
