/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_victorcruz;

/**
 *
 * @author Victor Jafet Cruz
 */
public class Lab8P2_VictorCruz extends javax.swing.JFrame {

    /**
     * Creates new form Lab8P2_VictorCruz
     */
    public Lab8P2_VictorCruz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        JB_LogOff = new javax.swing.JButton();
        JB_SalirSistema = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTA_InfoCarros = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMI_CRUDCarros = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMI_BusquedaVIN = new javax.swing.JMenuItem();
        JMI_BusquedaCategoria = new javax.swing.JMenuItem();
        JMI_BusquedaAtributoLibre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        JB_LogOff.setText("LogOff");
        JB_LogOff.setFocusable(false);
        JB_LogOff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_LogOff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(JB_LogOff);

        JB_SalirSistema.setText("Salir del Sistema");
        JB_SalirSistema.setFocusable(false);
        JB_SalirSistema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JB_SalirSistema.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(JB_SalirSistema);

        JTA_InfoCarros.setColumns(20);
        JTA_InfoCarros.setRows(5);
        jScrollPane2.setViewportView(JTA_InfoCarros);

        jMenu1.setText("Admin Carros");

        JMI_CRUDCarros.setText("CRUD CARROS");
        JMI_CRUDCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CRUDCarrosActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_CRUDCarros);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Busqueda");

        JMI_BusquedaVIN.setText("Busqueda por VIN");
        JMI_BusquedaVIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_BusquedaVINActionPerformed(evt);
            }
        });
        jMenu2.add(JMI_BusquedaVIN);

        JMI_BusquedaCategoria.setText("Budqueda por Categoria");
        JMI_BusquedaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_BusquedaCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(JMI_BusquedaCategoria);

        JMI_BusquedaAtributoLibre.setText("Busqueda Atributo Libre");
        JMI_BusquedaAtributoLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_BusquedaAtributoLibreActionPerformed(evt);
            }
        });
        jMenu2.add(JMI_BusquedaAtributoLibre);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_CRUDCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CRUDCarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_CRUDCarrosActionPerformed

    private void JMI_BusquedaVINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_BusquedaVINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_BusquedaVINActionPerformed

    private void JMI_BusquedaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_BusquedaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_BusquedaCategoriaActionPerformed

    private void JMI_BusquedaAtributoLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_BusquedaAtributoLibreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMI_BusquedaAtributoLibreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab8P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab8P2_VictorCruz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_LogOff;
    private javax.swing.JButton JB_SalirSistema;
    private javax.swing.JMenuItem JMI_BusquedaAtributoLibre;
    private javax.swing.JMenuItem JMI_BusquedaCategoria;
    private javax.swing.JMenuItem JMI_BusquedaVIN;
    private javax.swing.JMenuItem JMI_CRUDCarros;
    private javax.swing.JTextArea JTA_InfoCarros;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
